apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redpanda-connect
  namespace: redpanda-connect
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: redpanda-connect
        namespace: redpanda-connect
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  #valuesFrom:
  #  - kind: ConfigMap
  #    name: pipeline-config
  #    valuesKey: pipeline.yaml
  values:
    tradier_session: "REPLACE_WITH_SECRET" # Placeholder
