apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redpanda-connect
  namespace: redpanda-connect
spec:
  interval: 30m
  chart:
    spec:
      chart: redpanda-connect
      version: "4.*"
      sourceRef:
        kind: HelmRepository
        name: redpanda-connect
        namespace: redpanda-connect
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      adminPassword: alex
