apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik 
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik 
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: traefik 
        namespace: traefik 
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
