apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redpanda-connect
resources:
  - ../../base/redpanda-connect/
  - redpanda-connect-configmap.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: pipeline-config
      data:
        pipeline.yaml: |
          config:
            input:
              label: ""
              websocket:
                url: wss://ws.tradier.com/v1/markets/events
                auto_replay_nacks: true
                open_message: '{"sessionid": "{{ .tradier_session }}", "symbols": ["AAPL", "SPY"]}'
                open_message_type: text
            output:
              stdout: {}
    target:
      kind: ConfigMap
      name: pipeline-config
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: tradier-session-secret-env
    namespace: redpanda-connect
    literals:
      - tradier_session=$(kubectl get secret tradier-session-secret -n redpanda-connect -o jsonpath='{.data.sessionid}' | base64 -d)
