apiVersion: v1
data:
  pipeline.yaml: |
    config:
      input:
        label: ""
        websocket:
          url: wss://ws.tradier.com/v1/markets/events
          auto_replay_nacks: true
          open_message: '{"sessionid": "TOBEADDED", "symbols": ["AAPL", "SPY"]}'
          open_message_type: text
      output:
        stdout: {}
kind: ConfigMap
metadata:
  name: pipeline-config
