apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
data:
  pipeline.yaml: |
    config:
      input:
        generate:
          interval: 2s
          mapping: |
            root = env("SESSION_ID")

      output:
        stdout:
          codec: lines

