   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: k8s-visualizer 
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: k8s-visualizer 
     template:
       metadata:
         labels:
           app: k8s-visualizer 
       spec:
         imagePullSecrets:
           - name: ghcr-secret
         containers:
           - name: k8s-visualizer 
             image: ghcr.io/alextreichler/k8svisualizer:1.0.6
             imagePullPolicy: Always
             ports:
               - containerPort: 8090
             env:
               - name: READ_ONLY 
                 value: "false"
               - name: ALLOWED_ORIGINS 
                 value: ""
